Citizen.CreateThread(function()
	while true do
		local pId = GetPlayerServerId(PlayerId())
		local name = GetPlayerName(PlayerId())
		SetDiscordAppId(1078741825348718722)
		SetDiscordRichPresenceAsset('Cinq')
		SetDiscordRichPresenceAssetText('freeroam NL_Dev')
		SetRichPresence("["..pId.."]"..name.." | "..#GetActivePlayers() .." / 4 Players")
		SetDiscordRichPresenceAssetSmall('Cinq')
		SetDiscordRichPresenceAssetText('click on one of the two buttons')
		 SetDiscordRichPresenceAction(0, " NL_Dev Discord", "https://discord.gg/UW8PDyAEvM")
		 SetDiscordRichPresenceAction(1, "NL_Dev Video", "https://www.youtube.com/channel/UCeVi1M0YgkmbuCS3Z_XWxow")
		Citizen.Waite(15000)
end
end)